### ISSUE TITLE
Social fixes

### ISSUE THREAD

**Issue by jacc** [stardewapp/stardew.app#33]
- [x] Sam's iconURL breaks the site @jacc 
- [x] Hearts don't work with the current slideover logic @clxmente 
- [x] Birthdays should be capitalized @jacc 
- [ ] Home and family should not show if no values @jacc 
- [ ] Icon in sidebar is stretched @jacc

**Comment by clxmente** [comment]
I don't think "Icon in sidebar is stretched" is accurate. The icon looks normal but if you want to switch the icon to something that looks better its fine by me. 🙂

**Comment by clxmente** [comment]
> Sam's iconURL breaks the site

it looks like there's some items in the NPC gift taste game files that are not actually in the game. For example, Sam has items `655` and `658` in his `loves` list which aren't actually in the game. I'll just remove any entries that don't appear in our `objects.json` file.
